name: Service Request
description: Request a new presence to be added to the store
labels: [service request]
body:
  - type: markdown
    attributes:
      value: |
        Before submitting a new request, ensure your service hasn't already been
        requested before. If it has, reply to the open issue instead.
  - type: input
    attributes:
      label: Website name
      description: The name of the website you want to see added
    validations:
      required: true
  - type: input
    attributes:
      label: Website URL
      description: The URL of the website you want to see added
    validations:
      required: true
  - type: input
    attributes:
      label: Website logo
      description: The logo of the website you want to see added
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: It is a paid service
        - label: It is region restricted
  - type: textarea
    validations:
      required: true
    attributes:
      label: Description
      description: Provide a detailed description on what you would like to see displayed on this presence
